### ISSUE TITLE
Outdated data from cdn url

### ISSUE THREAD

**Issue by occluder** [WFCD/warframe-relic-data#5]
It seems that the data fetched from the cdn url listed in readme (https://cdn.jsdelivr.net/gh/TitaniaProject/warframe-relic-data/data/Relics.min.json) is outdated, are there any plans on updating it? Or is this supposed to be a host-for-yourself type of project?

**Comment by Soundofdarkness** [comment]
Hey !
Sorry for the (extremely) late response. Currently I have no plans on updating it since I'm not running the CI system for it anymore.
You can probably run it yourself or on Github Actions relatively easily. Basically all the CI was doing is running `yarn export` (or `npm run export`) and then `./update.sh` to actually push the data to github. The access token was just a personal access token iirc.

**Comment by occluder** [comment]
Alrighty. Thanks.
