### ISSUE TITLE
work with WFCD?

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-relic-data#7]
hi, tobiah from @WFCD here.... interested in working with us?

I noticed you weren't maintaining some of your CI anymore, figured I'd see if you wanted to work together, incorporate this as part of warframe-items, then people could pull the data at their leisure from our api (https://api.warframestat.us)

**Comment by Soundofdarkness** [comment]
Hey,
in general I'm absolutely open to get this incorporated into warframe-items.
Would you have any recommendations on how this would work best ?
I could see if I have some time in the next day or two to at least test if the system still works currently, so we at least have an idea if parts of the code could be used. 
In any case, thanks for the offer !

**Comment by TobiTenno** [comment]
i'm thinking the best would be
1) adding any missing data that's parsed to our build in warframe-items
2) creating an artificial "relics" category that people can filter down to on instantiation of the Items class to get just what's provided by warframe-relic-data, or at least build a way in warframe-status to get just relics to make it a bit easier for people to grab them

**Comment by Soundofdarkness** [comment]
Sounds good !
Then I think I should probably try to fix the parser to a point that it actually generates working information again,
so we have a reference of what to implement if its missing (I will see if I can manage to already try to get most of the info from warframe-items, since I would hope that this should make it easier to implement in warframe-items)

So far this repository mainly adds the following mapping (excuse my poor attempt to show the format):
```
relic --> item drops when opened (with dropchances)
        |-> locations for getting the relic (with rarity + chance, but mission info is only as $planet-$mission format, so probably lacking information)
        |-> Warframe.market info (item id + url name)
        --> vaulted (only if vaulted or not based on if it has a registered drop)
```
I think most of the data for it should already be on your repository from a quick check, just probably split between multiple categories (namely Warframes and the weapon categories i think), with the exception of the warframe.market id/url part. However I'm not sure if you would consider the warframe-market id's to be in scope for warframe-items. 
So in the end I would guess the main thing that could be useful would be the correlation for looking up relics.

**Comment by TobiTenno** [comment]
i know a bunch of people don't like how my current "vault date" works, so a boolean would probably be better anyway, and warframe.market info should be pretty helpful since a lot of people use that for downstream stuff and it'd be helpful to have it directly in the data, just to make it easier to potentially fetch them en-masse

**Comment by Soundofdarkness** [comment]
To me that sounds like maybe having both vault-date + the boolean could be an idea too, since that would give easy access to just checking if the relic can be farmed, or the more advanced info for display purposes.
And sure, if wfm-id's can be useful I can see about adding them too.

**Comment by Soundofdarkness** [comment]
Alright, I've started to create a working parser again that only depends on WFCD data and the WFM api.
So far its only written and typescript, since i felt like its easier to get the logic working that way, but converting that to javascript shouldn't be an issue. 
I'm just not sure if the current data structure is a good idea or too nested (Type is TitaniaRelic in [Types.ts](https://github.com/TitaniaProject/warframe-relic-data/blob/development/src/Types.ts)). 

The proof of concept is in the [development](https://github.com/TitaniaProject/warframe-relic-data/tree/development) branch.
Aside from the type things I just dont know if loading the json from github is in any form an idea or if that needs to be changed (the main problem here would be warframe-drop-data, since warframe-patchlogs is just used for grabbing the game version, and will ofc not be needed again in warframe-items) .

**Comment by TobiTenno** [comment]
drop data is all available from the api as well, but I can look at it and try to start up a parallel branch if we're interested it in just being part of the warframe-items build

**Comment by Soundofdarkness** [comment]
That sounds like an idea, but considering how much content the drop data has it might still make sense to keep it in a seperate module. And about the API, i completely forgot that I can load it from there instead of GH directly.. But drops.warframestat.us should be the data from the repository right ? As then I can probably just switch the URL in the config to it for now.

**Comment by TobiTenno** [comment]
yeah. drops.warframestat.us/data is the data that's in the repo

**Comment by Soundofdarkness** [comment]
Alright, seems like that works now too. (And at least the code still works now so it *might* be stable).
How would you suggest to procceed with integrating the code in warframe-items ?

**Comment by TobiTenno** [comment]
well, couple steps, depending on how deep you wanna go:
- if you want us to own it in the long run, migrating the repo
- if you just wanna copy code over, feel free to make a PR into warframe-items to insert the data where you feel appropriate
- if you wanna keep code separate and as a separate org entirely, just a PR consuming the library from npm and then assuming we can do a build as needed, add that as part of our build, or just pull data from it like we do for warframe-patchlogs

**Comment by Soundofdarkness** [comment]
I would guess for long term the best choice would be to migrate the repo, since then I can still help maintain it(I guess that should still be possible ?) when my life is not too chaotic, but whenever I can't there is still a chance/option that someone else of your group/team can try to fix it without me needing to be there. 

And well, for short term we could either directly migrate or I could publish the development branch as a package and expose the functions to build the project and we could integrate it as part of the warframe-items build. Overall that might be a good option even with the repo being migrated ? 

But I'm open to putting the code into warframe-items too if that's the better option.

**Comment by TobiTenno** [comment]
> I guess that should still be possible

100%, i'll give you admin perms on the repo if we migrate it so if you ever want to move it out, you have the power to do that

> I could publish the development branch as a package and expose the functions to build the project and we could integrate it as part of the warframe-items build

i think this and migrating would be the simplest for integrating it long-term so it's not lost in the weeds of all the build, and i think i can give you perms to publish to the `@wfcd` namespace if you want, that way it's easier to find?

**Comment by Soundofdarkness** [comment]
Alright, sounds good to me !
Then I will see about getting the build process exposed so warframe-items can actually call it directly and configure it and getting the package ready to be actually used.
And the namespace thing sounds like a good idea I think when the package is ready.
Thank you !

**Comment by Soundofdarkness** [comment]
Alright, in theory the module should be usable from external now.
I've added the option to generate and write the data to a specified folder (with filename options), or to just directly access it after the generation is done.

Is there anything else that should be done before starting to migrate and integrate the project ? 
(And I'm not quite sure if the naming of the classes is okay or if it would be confusing due to the generic naming, like "Generator" and "VersionChecker")

**Comment by TobiTenno** [comment]
if it's published, i'll give that a shot. i think generic naming is great, cause i can scope it myself if needed.

**Comment by Soundofdarkness** [comment]
So far i've only published it on github: [development](https://github.com/TitaniaProject/warframe-relic-data/tree/development), but it should be installable with `npm install TitaniaProject/warframe-relic-data#development`, but for use as a module i would probably need to publish it with the compiled code and not just in source form.

**Comment by TobiTenno** [comment]
most likely, cause i'm not running a TS project, so i'd need the compiled copy (it should ship with types that way, right?)

**Comment by TobiTenno** [comment]
oh, i found one part that's gonna be an issue. this calls out to the api to pull the old items.... is there any way we could feed it a separate list of existing items to run on the items being generated in the build of items itself so it's not working off of old data to build new data? i just forsee that could cause weird update lag...

**Comment by TobiTenno** [comment]
thinking about that, though, it's nice for the ability to generate it all ahead of time instead of doing most of the generation on items, call the relics generator, then apply more data on the item

**Comment by TobiTenno** [comment]
thinking that way, i think keep it how it is now on that front, but for typescript purposes, your Types.d.ts probably needs a module scoped on it so it's less likely to pollute... or at least easier to use

**Comment by Soundofdarkness** [comment]
I've now added the compiled JS into the repo (probably not the best solution, but for short term testing it should be okay), so the npm install works properly and the module is usable afterwards from normal JS code.

For the API calls, I can totally add something to feed separate data in instead of calling the API (in fact, this should already nearly be possible with just calling the same functions than generate (except `fetchRawData`) and prefilling the arrays on the Generator instance).

Well, both ahead-of-time and calling the generator in the main generation process should be doable, the only issue would be that adding the data that is produced here on the normal items might cause some duplicated information, so that would probably be something that needs to be transformed before being merged.

And for the module scoping: I *think* its not needed here, since the Types.d.ts should be generated correctly for the module by the typescript compiler (and my current Types.ts is not user facing in the end). So far the [index.d.ts](https://github.com/TitaniaProject/warframe-relic-data/blob/a9ff5e5031c5488256e45951f77c234637eb7907/dist/index.d.ts) that I'm exposing as type "entry point" should isolate the module correctly. But I will read around a bit more on the topic to see if I need some sort of scoping (that would just require me to write the types manually, so I'd be surprised if that's required to make it properly isolated).

**Comment by TobiTenno** [comment]
hmmm, i must be trying to reference them in my jsdoc wrong, then, because i'm getting non-existent module messages

**Comment by Soundofdarkness** [comment]
Do you get those on some sort of jsdoc lint ? As the normal 
```js
/**
 * @type {import("warframe-relic-data").TitaniaRelic}
 */
``` 
seem to work for me, unless you meant something else.

**Comment by TobiTenno** [comment]
right, that would work if i was using ESM, but i don't think import works on CJS? maybe i'm just thinking of the wrong part... i guess i should ask first, are you using that in a CJS file or an ESM file?

**Comment by Soundofdarkness** [comment]
I was using that in a CJS file, as far as i know that import syntax is specific to jsdoc in that case (or maybe just to vscode, I'm not sure). But I'm not sure if that's the correct or normal way to handle this to be fair.

**Comment by TobiTenno** [comment]
i put some related changes in #8, but if you could join [our discord](https://discord.gg/jGZxH9f), we can talk faster/easier...

**Comment by TobiTenno** [comment]
i've got a build out for pulling this in. i'd rather use the module version of warframe-relic-data before pulling fully into master on items

https://github.com/WFCD/warframe-items/pull/374

**Comment by Soundofdarkness** [comment]
Just merged the PR, I can work on the rest soon, but might still take a day or two.
I'm Laurelianae#9542 on your discord (pretty sure I'm already in the channel for warframe-items)

**Comment by TobiTenno** [comment]
oh! cool!

**Comment by Soundofdarkness** [comment]
Thanks for the role !  I hope I can help a bit 😃

**Comment by TobiTenno** [comment]
the merges worked out, and it's auto-publishing now! semantic-release reduced it to v1.0.0, so that's annoying, but we'll get it bumped manually soon:tm:

**Comment by Soundofdarkness** [comment]
Nice ! Thank you !
I will probably work on adding the relevant links and maybe badges to the readme today evening.
